name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  skip-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show files
        run: ls -R
